Add persistent resource parsing to pipeline
osic/qa-jenkins-onmetal pull request #17
Opened 2016-11-02 16:03 UTC by antwash

2016-11-02 20:25 UTC, castulo requested changes

2016-11-02 20:25 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
> +    git clone https://github.com/osic/persistent-resources-tests-parse.git
I would like the repo to be cloned to a specific known location instead of just wherever the home is

2016-11-02 20:25 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
> +    pip install -e /root/persistent-resources-tests-parse
Why are you installing this repo in development mode? At this point this should be an official repo.

2016-11-02 21:36 UTC, antwash commented on jenkins/osa_onmetal.functions.groovy
> +    pip install -e /root/persistent-resources-tests-parse
For some reason the package will not install if it's not install in development mode.. I researched about it and the solutions presented to solved problem my package met the requirements already but it still didn't install correctly.

2016-11-03 17:04 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
>      pip install -e /root/persistent-resources-tests-parse
So why are you installing this in development mode? (using the -e option)

2016-11-03 18:04 UTC, antwash commented on jenkins/osa_onmetal.functions.groovy
>      pip install -e /root/persistent-resources-tests-parse
For some reason the package will not install if it's not install in development mode.. I researched about it and the solutions presented to solved problem my package met the requirements already but it still didn't install correctly.

2016-11-03 18:31 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
>      pip install -e /root/persistent-resources-tests-parse
Your setup.py is wong, you are not specifying there what files/packages you want to include in your package. Add that to your setup.py or setup.cfg and that should work. If you have questions let me know and I can help, but we cannot integrate this in dev mode.

2016-11-03 19:41 UTC, castulo approved these changes

2016-11-03 19:42 UTC, merged