Added new method install_parser, added parsing status files
osic/qa-jenkins-onmetal pull request #26
Opened 2016-11-22 23:58 UTC by lamarwhitej

Added new method install_parser, added parsing status files.  Fixed issue with already installed elastic-benchmark by removing it if it is there then reinstalling.  It should do this anyway in case there have been updates.

2016-11-23 20:32 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
>      sudo pip install -e elastic-benchmark
Why are you installing the package in development mode? This should be installed as an official package now:
pip install elastic-benchmark/

2016-11-23 20:35 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
>      '''
Why are you also installing elastic-benchmark here manually?

2016-11-23 20:36 UTC, castulo requested changes
I added a couple of comments that need to be addressed first.

2016-12-05 19:34 UTC, lamarwhitej commented
Hey Cas let's just close this one.  I have some file changes that I need to get added.  I changed some file names in the during tests.  The pipeline is expecting different ones.

2016-12-05 19:34 UTC, closed without merging