Integrate During Test
osic/qa-jenkins-onmetal pull request #6
Opened 2016-10-18 20:03 UTC by lamarwhitej

Add during test to the osa_onmetal groovy script.  Setup, Start, Stop, Aggregate data.

2016-10-18 20:08 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
> +    scp -o StrictHostKeyChecking=no -r /home/ubuntu/workspace/Joshs_sandbox@3/during-upgrade-tests root@${host_ip}:/root
Why are you using this hardcoded path that is referring to a local jenkins workspace? Joshs_sandbox@3

2016-10-18 20:11 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
> +def setup_during_test(host_ip) {
I'd prefer if this function is called something like install_during_upgrade_tests so it is consistent with the other upgrade tests suites like install_persistent_resources_tests

2016-10-18 20:13 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
> +def aggregate_results(host_ip) {
This function name is very vague, it does not specify what results is aggregating, is it aggregating all tests result? if that is so then it should be fine, if it only aggregates results from one test suite then a more specific name may be better

2016-10-18 20:14 UTC, CasJ commented on jenkins/osa_onmetal.functions.groovy
> +  python elastic-benchmark/elastic_benchmark.upgrade.py
Same comment as above, does this method parses all the results or only those belonging to one test suite?

2016-10-18 20:15 UTC, castulo requested changes
I see your pull request is also missing the part where those functions are actually being used in the pipeline. And you need to rebase your code.

2016-10-18 22:54 UTC, dlux commented on jenkins/osa_onmetal.functions.groovy
> +    scp -o StrictHostKeyChecking=no -r /home/ubuntu/workspace/Joshs_sandbox@3/during-upgrade-tests root@${host_ip}:/root
Agree review sintaxis...

2016-10-19 00:58 UTC, lamarwhitej commented on jenkins/osa_onmetal.functions.groovy
> +  python elastic-benchmark/elastic_benchmark.upgrade.py
This isn't finished, but it parse all of them and push them to elastic search.

2016-10-19 01:00 UTC, lamarwhitej commented on jenkins/osa_onmetal.functions.groovy
> +def aggregate_results(host_ip) {
Yes this will pull for all of them.

2016-10-19 01:00 UTC, lamarwhitej commented on jenkins/osa_onmetal.functions.groovy
> +    scp -o StrictHostKeyChecking=no -r /home/ubuntu/workspace/Joshs_sandbox@3/during-upgrade-tests root@${host_ip}:/root
Forgot to remove from testing.

2016-10-19 17:52 UTC, CasJ commented
I'm closing this PR since I think all the comments were addressed in a separate PR.

2016-10-19 17:52 UTC, closed without merging